version: "2"

services:
  dotnet:
    build: ./build/docker/dev/dotnet
    container_name: app-dev-dotnet
    environment:
      - DEVENV=dev
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    links:
      - db
    ports:
      - "48001:5000"
    volumes:
      - ./dotnet:/mnt/dotnet
  ui:
    build: ./build/docker/dev/ui
    container_name: app-dev-ui
    environment:
      - DEVENV=dev
    ports:
      - "48002:4000"
    volumes:
      - ./ui:/ui
  nginx:
    build: ./build/docker/dev/nginx
    container_name: app-dev-nginx
    links:
      - dotnet
      - ui
    ports:
      - "48000:80"
  db:
    image: mysql:5.7.17
    container_name: app-dev-db
    environment:
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "48004:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6
    container_name: app-dev-phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=test
    links:
      - db
    ports:
    - "48003:80"
