apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boxboat-blog-prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: boxboat-blog-prod
    spec:
      containers:
      - name: nginx
        command: ["sh", "-c", "echo '127.0.0.1 dotnet nginx ui-ssr' > /etc/hosts && nginx -g 'daemon off;'"]
        image: dtr.caleb.boxboat.net/boxboat/boxboat-blog-nginx:1
        env:
        - name: DEVENV
          value: prod
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "1m"
      - name: dotnet
        command: ["sh", "-c", "echo '127.0.0.1 dotnet nginx ui-ssr' > /etc/hosts && ln -s /etc/secrets/boxboat-blog-db/config /dotnet/App/src/App/Common/Config/config.prod.json && dotnet App.dll"]
        image: dtr.caleb.boxboat.net/boxboat/boxboat-blog-dotnet:1
        env:
        - name: DEVENV
          value: prod
        volumeMounts:
        - name: boxboat-blog-db
          mountPath: /etc/secrets/boxboat-blog-db
          readOnly: true
        resources:
          requests:
            cpu: "1m"
      - name: ui-ssr
        command: ["sh", "-c", "echo '127.0.0.1 dotnet nginx ui-ssr' > /etc/hosts && node server.js"]
        image: dtr.caleb.boxboat.net/boxboat/boxboat-blog-ui-ssr:1
        env:
        - name: DEVENV
          value: prod
        resources:
          requests:
            cpu: "1m"
      volumes:
      - name: boxboat-blog-db
        secret:
          secretName: db-prod
